### ISSUE TITLE
Condense fluo.sh

### ISSUE THREAD

**Issue by jkosh44** [apache/fluo#1084]
After the changes done in #1083 the Java entry point for all the commands is the same class, [FluoProgram](https://github.com/apache/fluo/blob/master/modules/command/src/main/java/org/apache/fluo/command/FluoProgram.java). This has led to some duplication in the [fluo](https://github.com/apache/fluo/blob/master/modules/distribution/src/main/scripts/fluo) script, specifically in the case statement at the end. Some work could be done to remove the duplication and condense the script.

**Comment by ZoukeNN** [comment]
Hi @jkosh44 ,
Im new to this project, Before I start to refactor the script, I would like to explain how I would refactor to make sure I am not missing anything.

The last case statement starts at line no - 129 , Inside this case body there are lot calls to $JAVA org.apache.fluo.command.FluoProgram with different arguments like
-  $JAVA org.apache.fluo.command.FluoProgram $1 
-  $JAVA org.apache.fluo.command.FluoProgram $1 -h
-  $JAVA org.apache.fluo.command.FluoProgram "$@"
so on...

My idea is create a function which accepts arguments for running Java.. Here are a list of arguments 
1. Java Class Name
2. List of arguments to Java program

By doing this, We can make the script more reusable. Please let me know if I am on the right track? Are there any important points I'm missing?. If I am on the right track . I will start working on refactoring the code.

Best Regards,
Bhuvan.

**Comment by ctubbsii** [comment]
@ZoukeNN Creating a bash function to collapse some things seems like a good idea. Additionally, some cases could be combined that have identical bodies.

Example:
```bash
config|get-jars)
  check_conn_props
  $JAVA org.apache.fluo.command.FluoProgram "$@"
  ;;
status|wait)
  $JAVA org.apache.fluo.command.FluoProgram "$@"
  ;;
```

Also, be sure to use [shellcheck](https://github.com/koalaman/shellcheck) to check for potential problems.

**Comment by jkosh44** [comment]
I agree with @ctubbsii. For testing you can use [fluo-uno](https://github.com/apache/fluo-uno/) to set up your local environment and you can use [stresso](https://github.com/apache/fluo-examples/tree/master/stresso) as a test app.

Don't hesitate at all if you have any questions, we're happy to help.

**Comment by ZoukeNN** [comment]
I am glad you guys are there to support me, I am trying to setup my local dev environment.  I am facing few issues while trying to run fluo-uno.
```Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Loading configuration from /home/flyingcanopy/fluo-uno/install/accumulo-2.0.0/conf/accumulo-client.properties
2020-03-09 02:04:26,278 [start.Main] ERROR: Thread 'shell' died.
java.lang.RuntimeException: Instance name uno does not exist in zookeeper. Run "accumulo org.apache.accumulo.server.util.ListInstances" to see a list.
	at org.apache.accumulo.core.clientImpl.ClientContext.getInstanceID(ClientContext.java:400)
	at org.apache.accumulo.core.clientImpl.InstanceOperationsImpl.getInstanceID(InstanceOperationsImpl.java:239)
	at org.apache.accumulo.shell.Shell.printInfo(Shell.java:631)
	at org.apache.accumulo.shell.Shell.start(Shell.java:533)
	at org.apache.accumulo.shell.Shell.execute(Shell.java:517)
	at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:129)
	at java.base/java.lang.Thread.run(Thread.java:830).
```
Someone else faced this issue before and resolved it - [Instance name uno does not exist in zookeeper #224](https://github.com/apache/fluo-uno/issues/224). Although the issue he faced and I faced are the same as seen from the logs. I am assuming the cause of the issue might not be the same , hence the fix that he applied is not working for me. Please Let me know if you know how to fix this issue?

**Comment by ZoukeNN** [comment]
> I am glad you guys are there to support me, I am trying to setup my local dev environment(Ubuntu). I am facing few issues while trying to run fluo-uno.
> 
> ```java
> Loading configuration from /home/flyingcanopy/fluo-uno/install/accumulo-2.0.0/conf/accumulo-client.properties
> 2020-03-09 02:04:26,278 [start.Main] ERROR: Thread 'shell' died.
> java.lang.RuntimeException: Instance name uno does not exist in zookeeper. Run "accumulo org.apache.accumulo.server.util.ListInstances" to see a list.
> 	at org.apache.accumulo.core.clientImpl.ClientContext.getInstanceID(ClientContext.java:400)
> 	at org.apache.accumulo.core.clientImpl.InstanceOperationsImpl.getInstanceID(InstanceOperationsImpl.java:239)
> 	at org.apache.accumulo.shell.Shell.printInfo(Shell.java:631)
> 	at org.apache.accumulo.shell.Shell.start(Shell.java:533)
> 	at org.apache.accumulo.shell.Shell.execute(Shell.java:517)
> 	at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:129)
> 	at java.base/java.lang.Thread.run(Thread.java:830).
> ```
> 
> Someone else faced this issue before and resolved it - [Instance name uno does not exist in zookeeper #224](https://github.com/apache/fluo-uno/issues/224). Although the issue he faced and I faced are the same as seen from the logs. I am assuming the cause of the issue might not be the same , hence the fix that he applied is not working for me. Please Let me know if you know how to fix this issue?

**Comment by ctubbsii** [comment]
Are there any more details in the log files in `${YOUR_UNO_DIR}/install/logs/accumulo/*` or `${YOUR_UNO_DIR}/install/logs/setup/*`?

**Comment by ZoukeNN** [comment]
I see this in /install/logs/setup/accumulo.err

`Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2020-03-09 08:57:02,347 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /home/flyingcanopy/fluo-uno/install/accumulo-2.0.0/conf/accumulo.properties
2020-03-09 08:57:03,708 [init.Initialize] INFO : Hadoop Filesystem is hdfs://localhost:8020
2020-03-09 08:57:03,709 [init.Initialize] INFO : Accumulo data dirs are [hdfs://localhost:8020/accumulo]
2020-03-09 08:57:03,709 [init.Initialize] INFO : Zookeeper server is localhost:2181
2020-03-09 08:57:03,710 [init.Initialize] INFO : Checking if Zookeeper is available. If this hangs, then you need to make sure zookeeper is running
2020-03-09 08:57:03,922 [init.Initialize] ERROR: Fatal exception
java.io.IOException: Failed to check if filesystem already initialized
	at org.apache.accumulo.server.init.Initialize.checkInit(Initialize.java:285)
	at org.apache.accumulo.server.init.Initialize.doInit(Initialize.java:323)
	at org.apache.accumulo.server.init.Initialize.execute(Initialize.java:991)
	at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:129)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.net.ConnectException: Call From ubuntu/192.168.65.128 to localhost:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:833)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:757)
	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1549)
	at org.apache.hadoop.ipc.Client.call(Client.java:1491)
	at org.apache.hadoop.ipc.Client.call(Client.java:1388)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:233)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:118)
	at com.sun.proxy.$Proxy19.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:907)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy20.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1666)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1576)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1573)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1588)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1683)
	at org.apache.accumulo.server.fs.VolumeManagerImpl.exists(VolumeManagerImpl.java:254)
	at org.apache.accumulo.server.init.Initialize.isInitialized(Initialize.java:860)
	at org.apache.accumulo.server.init.Initialize.checkInit(Initialize.java:280)
	... 4 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:579)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:820)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:533)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:700)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:804)
	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:421)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1606)
	at org.apache.hadoop.ipc.Client.call(Client.java:1435)
	... 28 more
2020-03-09 08:57:03,928 [start.Main] ERROR: Thread 'init' died.
java.lang.RuntimeException: java.io.IOException: Failed to check if filesystem already initialized
	at org.apache.accumulo.server.init.Initialize.execute(Initialize.java:997)
	at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:129)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.io.IOException: Failed to check if filesystem already initialized
	at org.apache.accumulo.server.init.Initialize.checkInit(Initialize.java:285)
	at org.apache.accumulo.server.init.Initialize.doInit(Initialize.java:323)
	at org.apache.accumulo.server.init.Initialize.execute(Initialize.java:991)
	... 2 more
Caused by: java.net.ConnectException: Call From ubuntu/192.168.65.128 to localhost:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:833)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:757)
	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1549)
	at org.apache.hadoop.ipc.Client.call(Client.java:1491)
	at org.apache.hadoop.ipc.Client.call(Client.java:1388)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:233)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:118)
	at com.sun.proxy.$Proxy19.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:907)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy20.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1666)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1576)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1573)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1588)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1683)
	at org.apache.accumulo.server.fs.VolumeManagerImpl.exists(VolumeManagerImpl.java:254)
	at org.apache.accumulo.server.init.Initialize.isInitialized(Initialize.java:860)
	at org.apache.accumulo.server.init.Initialize.checkInit(Initialize.java:280)
	... 4 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:579)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:820)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:533)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:700)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:804)
	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:421)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1606)
	at org.apache.hadoop.ipc.Client.call(Client.java:1435)
	... 28 more`

**Comment by ctubbsii** [comment]
That error seems to indicate that Hadoop itself didn't start. So, you should probably check the Hadoop logs next. My instinct says that it's because the Hadoop script tried to ssh to localhost to complete the setup, and you probably don't have passwordless authentication set up over ssh. (https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-common/SingleCluster.html#Setup_passphraseless_ssh), but you may have to confirm with the Hadoop or setup logs.

**Comment by ZoukeNN** [comment]
@ctubbsii you were right , I checked the logs and the issues seems to be with not having passwordless authentication. 

This did the work
`
ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa 
`
`
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
`
Currently I am able to access uno shell.

**Comment by ctubbsii** [comment]
> @ctubbsii you were right , I checked the logs and the issues seems to be with not having passwordless authentication.

Great! Glad you got it working.

**Comment by flyingcanopy** [comment]
> I agree with @ctubbsii. For testing you can use [fluo-uno](https://github.com/apache/fluo-uno/) to set up your local environment and you can use [stresso](https://github.com/apache/fluo-examples/tree/master/stresso) as a test app.
> 
> Don't hesitate at all if you have any questions, we're happy to help.

@jkosh44 

When i try to package stresso . I am facing this issue.
```

[WARNING] The POM for org.apache.accumulo:accumulo-maven-plugin:jar:2.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.577 s
[INFO] Finished at: 2020-05-24T05:50:44-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.accumulo:accumulo-maven-plugin:2.0.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.apache.accumulo:accumulo-maven-plugin:jar:2.0.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```
Currently I am using 
```
Os: Ubuntu 18.04.4 LTS
Maven : 3.6.0
Java:
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
Please let me know if you can help me with this issue? I have made changes to fluo.sh. I need to test it.

**Comment by keith-turner** [comment]
@flyingcanopy I think I know why stresso is not building for you.  The source code for stresso is targeted at the last released version of Fluo, 1.2.0.  To build stresso against the latest unrelease Fluo code, you need to patch stresso with the changes in the PR apache/fluo-examples#11.  Let me know if you need any assistance with this.

**Comment by flyingcanopy** [comment]
@keith-turner 
I checked out fluo-130-update and ran the build and it was successful, However when I run `fluo init -a stresso -p conf/fluo-app.properties`

I am facing this issue 
`fluo init -a stresso -p conf/fluo-app.properties
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/curator/framework/CuratorFramework
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.beust.jcommander.Parameterized.parseArg(Parameterized.java:127)
	at com.beust.jcommander.JCommander.addDescription(JCommander.java:594)
	at com.beust.jcommander.JCommander.createDescriptions(JCommander.java:587)
	at com.beust.jcommander.JCommander.addCommand(JCommander.java:1533)
	at com.beust.jcommander.JCommander.addCommand(JCommander.java:1512)
	at com.beust.jcommander.JCommander.addCommand(JCommander.java:1519)
	at com.beust.jcommander.JCommander$Builder.addCommand(JCommander.java:1184)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at org.apache.fluo.command.FluoProgram.runFluoCommand(FluoProgram.java:41)
	at org.apache.fluo.command.FluoProgram.main(FluoProgram.java:33)
Caused by: java.lang.ClassNotFoundException: org.apache.curator.framework.CuratorFramework
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 13 more
`

I need help with this issue.

**Comment by jkosh44** [comment]
@flyingcanopy make sure that before you run `fluo init` that you build stresso using `./bin/build.sh` that should download all the jars and copy them to the right place.

**Comment by keith-turner** [comment]
@flyingcanopy here are complete instructions that should take you from a clean Ubuntu 18.04 instance to running the test.

```bash
# From https://github.com/apache/fluo-uno/blob/master/docs/ubuntu1804.md
sudo apt update
sudo apt install -y openjdk-11-jdk maven git openssh-server wget libxml2-utils make g++ libsnappy1v5
ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
ssh-keyscan -H localhost >> ~/.ssh/known_hosts
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
sed -i '/# for examples/a export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64' ~/.bashrc
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64


mkdir fluo-1084
cd fluo-1084

# Get software sources, would want to include your fluo changes
git clone https://github.com/apache/fluo.git
git clone https://github.com/apache/fluo-examples.git
git clone https://github.com/apache/fluo-uno.git
# patch stress to work with latest fluo
cd fluo-examples
git checkout -b update-for-200
git pull https://github.com/keith-turner/fluo-examples.git fluo-130-update
cd ..

#build Fluo Snapshot version
cd fluo
# Since we are working with unreleased version of Fluo, need to install it to local maven repo.
# This makes it available for stresso later
mvn clean install -PskipQA

# Use Uno to setup Fluo’s deps
cd ../fluo-uno
# edit conf/uno.conf and set FLUO_REPO to fluo source dir.  This will cause fetch below to build a
# fluo tar ball.
sed -i "s:#export FLUO_REPO=/path/to/fluo:export FLUO_REPO=/home/ubuntu/fluo-1084/fluo:g" conf/uno.conf 
# download software
./bin/uno fetch fluo
# run software
./bin/uno setup fluo
# set env vars, this helps stresso find Fluo and Accumulo setup in previous step
source <(./bin/uno env)

# Run stresso
cd ../fluo-examples/stresso
cp conf/env.sh.example conf/env.sh
./bin/build.sh
mkdir -p logs
# change MAPS, REDUCES, and SPLITS to 3.  This will make things run faster on a single node.
nano conf/env.sh
fluo init -a stresso -p conf/fluo-app.properties
fluo oracle -a stresso &> logs/oracle.log &
fluo worker -a stresso &> logs/worker.log &
# TODO edit splits to speed up test
./bin/run-test.sh

# kill oracle and worker process started earlier
kill %1 %2
# remove stresso fluo app
fluo remove -a stresso

# run test again if needed
fluo init -a stresso -p conf/fluo-app.properties
fluo oracle -a stresso &> logs/oracle.log &
fluo worker -a stresso &> logs/worker.log &
# TODO edit splits to speed up test
./bin/run-test.sh
```

One easy way to get a clean Ubuntu 18.04 instance is to use [multipass](https://multipass.run/).  The following command will start up a clean ubuntu 18.04 instance using multipass to run the commands above.

```bash
multipass launch -n stresso -m 8G -c 4 -d 16G bionic
multipass shell stresso
```

**Comment by flyingcanopy** [comment]
@keith-turner  thanks for clear instructions.
@jkosh44  which version of org.apache.commons.lang are we using ? maybe I can add the dependency in pom.xml. 
`fluo init -a stresso -p conf/fluo-app.properties
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang/exception/NestableException
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.fluo.command.CommandUtil.resolveFluoConfig(CommandUtil.java:53)
	at org.apache.fluo.command.FluoInit.main(FluoInit.java:111)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.exception.NestableException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 14 more
`

**Comment by flyingcanopy** [comment]
Hi,
 I get this when i run run-test.sh
```
*****Wait for Fluo to finish processing*****
2020-05-28 03:17:03,776 [clientImpl.ServerClient] WARN : There are no tablet servers: check that zookeeper and accumulo are running.
```
I believe its in waiting state for this statement  `**$FLUO_CMD wait -a $FLUO_APP_NAME**`
Can you please tell me how long does it  take for it to run  ? The process is in waiting state for > 45 minutes and I had to terminate it.
My config
```# Maximum number to generate
MAX=$((10**9))
#the number of splits to create in table
SPLITS=3
# Number of mappers to run for data generation, which determines how many files
# generation outputs.  The number of files determines how many mappers loading
# data will run.
MAPS=3
# Number of reduce tasks
REDUCES=3
# Number of random numbers to generate initially
GEN_INIT=$((10**6))
# Number of random numbers to generate for each incremental step.
GEN_INCR=$((10**3))
# Number of incremental steps.
ITERATIONS=3
```

Do I need to make any further changes ?

**Comment by flyingcanopy** [comment]
Thank you @keith-turner for clear instructions and @jkosh44 for guiding me through.
I was able to test the changes after refactoring fluo.sh.  Please merge, You can see the console output below. 
`
./bin/run-test.sh
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/flyingcanopy/Desktop/final_test/fluo-1084/fluo-uno/install/accumulo-2.0.0/lib/slf4j-log4j12-1.7.26.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/flyingcanopy/Desktop/final_test/fluo-1084/fluo-uno/install/apache-zookeeper-3.5.7-bin/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
*****Presplitting table*****
*****Generating and loading initial data set*****
Deleted /stresso/initTmp
*****Generating and loading incremental data set 1*****
*****Generating and loading incremental data set 2*****
*****Generating and loading incremental data set 3*****
*****Calculating # of unique integers using MapReduce*****
		UNIQUE=323
*****Wait for Fluo to finish processing*****
2020-05-28 05:45:41,150 [oracle.OracleClient] INFO : Connected to oracle at ubuntu:12926
2020-05-28 05:45:41,551 [zookeeper.ZooCache] WARN : Unhandled: WatchedEvent state:Closed type:None path:null
*****Printing # of unique integers calculated by Fluo*****
2020-05-28 05:45:44,425 [util.NativeCodeLoader] WARN : Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2020-05-28 05:45:45,455 [sasl.SaslDataTransferClient] INFO : SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2020-05-28 05:45:47,809 [metrics.ReporterUtil] INFO : Started 0 metrics reporters
2020-05-28 05:45:48,117 [oracle.OracleClient] INFO : Connected to oracle at ubuntu:12926
2020-05-28 05:45:48,570 [zookeeper.ZooCache] WARN : Unhandled: WatchedEvent state:Closed type:None path:null
Total at root : 323
Nodes Scanned : 1
*****Verifying Fluo & MapReduce results match*****
Success! Fluo & MapReduce both calculated 323 unique integers
`

**Comment by keith-turner** [comment]
Glad you got it to run @flyingcanopy.  I need to add those instructions I wrote up to fluo-examples.  When writing them up, I realized there are a lot of little gotchas.  

For the output of the test run, you can use the triple back tick.

https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by flyingcanopy** [comment]
> Glad you got it to run @flyingcanopy. I need to add those instructions I wrote up to fluo-examples. When writing them up, I realized there are a lot of little gotchas.
> 
> For the output of the test run, you can use the triple back tick.
> 
> https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

Thanks @keith-turner I edited and used the triple back tick ``` ```

**Comment by flyingcanopy** [comment]
> > Glad you got it to run @flyingcanopy. I need to add those instructions I wrote up to fluo-examples. When writing them up, I realized there are a lot of little gotchas.
> > For the output of the test run, you can use the triple back tick.
> > https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks
> 
> Thanks @keith-turner I edited and used the triple back tick ` `

Just let me know if there is anything else I can help with ?

**Comment by flyingcanopy** [comment]
> > > Glad you got it to run @flyingcanopy. I need to add those instructions I wrote up to fluo-examples. When writing them up, I realized there are a lot of little gotchas.
> > > For the output of the test run, you can use the triple back tick.
> > > https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks
> > 
> > 
> > Thanks @keith-turner I edited and used the triple back tick ` `
> 
> Just let me know if there is anything else I can contribute or help ?

**Comment by keith-turner** [comment]
> Just let me know if there is anything else I can contribute or help ?

Is there any particular area you are interested in?

**Comment by keith-turner** [comment]
This was done in #1098

**Comment by flyingcanopy** [comment]
> > Just let me know if there is anything else I can contribute or help ?
> 
> @flyingcanopy is there any particular area you are interested in?

Yes,  I am interested in algorithms.
