### ISSUE TITLE
Curator is throwing Exception in a background thread during integration tests

### ISSUE THREAD

**Issue by mikewalch** [apache/fluo#167]
I am seeing the exception below while running the integration tests.  It's not causing tests to fail. I think it's just due to a timing issue where curator is being used before it was started.  

Curator should be started before returning from SharedResources.  This could be done in SharedResource.getCurator() or in the SharedResources constructor when curator is created.  It could also be add to the utility method described in #166.

```
java.lang.IllegalStateException: Client is not started
    at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
    at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:113)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:474)
    at org.apache.curator.framework.imps.CreateBuilderImpl.performBackgroundOperation(CreateBuilderImpl.java:478)
    at org.apache.curator.framework.imps.OperationAndData.callPerformBackgroundOperation(OperationAndData.java:65)
    at org.apache.curator.framework.imps.CreateBuilderImpl$10.callPerformBackgroundOperation(CreateBuilderImpl.java:656)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:789)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:487)
    at org.apache.curator.framework.imps.CreateBuilderImpl.pathInBackground(CreateBuilderImpl.java:660)
    at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:439)
    at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
    at org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode.createNode(PersistentEphemeralNode.java:340)
    at org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode.access$000(PersistentEphemeralNode.java:52)
    at org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode$1.process(PersistentEphemeralNode.java:69)
    at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:61)
    at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522)
    at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
```

**Comment by kpm1985** [comment]
I was searching for another issue and I think this is closed by #1035
