### ISSUE TITLE
fluo yarn start fails with UnknownHostException

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#345]
`fluo yarn start` is no longer working for me.  Using `git bisect` I determined it starts failing after 87e8062db1b28321e829cde4dbc8b3d1a300b8d

My env is a 20 node ec2 cluister running hadoop 2.3.0 and accumulo 1.6.1

```
$ ./fluo yarn start
05:15:13.141 [main] INFO  io.fluo.cluster.yarn.FluoTwillApp - Configuring a Fluo instance with 1 Oracle instances and 17 Worker instances with following properties:
05:15:13.147 [main] INFO  io.fluo.cluster.yarn.FluoTwillApp - io.fluo.oracle.max.memory.mb = 512
05:15:13.147 [main] INFO  io.fluo.cluster.yarn.FluoTwillApp - io.fluo.worker.max.memory.mb = 512
05:15:13.147 [main] INFO  io.fluo.cluster.yarn.FluoTwillApp - io.fluo.oracle.num.cores = 1
05:15:13.148 [main] INFO  io.fluo.cluster.yarn.FluoTwillApp - io.fluo.worker.num.cores = 2
05:15:13.209 [main] DEBUG io.fluo.cluster.yarn.YarnAdmin - Adding observer jar (fluo-stress-1.0.0-beta-1-SNAPSHOT.jar) to Fluo instance.
05:15:13.412 [main] ERROR o.a.twill.yarn.YarnTwillPreparer - Failed to submit application Fluo
java.net.UnknownHostException: Invalid host name: local host is: (unknown); destination host is: "ip-10-1-2-12":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_51]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_51]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_51]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_51]
    at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:783) ~[hadoop-common-2.3.0.jar:na]
    at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:742) ~[hadoop-common-2.3.0.jar:na]
    at org.apache.hadoop.ipc.Client$Connection.<init>(Client.java:400) ~[hadoop-common-2.3.0.jar:na]
    at org.apache.hadoop.ipc.Client.getConnection(Client.java:1448) ~[hadoop-common-2.3.0.jar:na]
    at org.apache.hadoop.ipc.Client.call(Client.java:1377) ~[hadoop-common-2.3.0.jar:na]
    at org.apache.hadoop.ipc.Client.call(Client.java:1359) ~[hadoop-common-2.3.0.jar:na]
    at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206) ~[hadoop-common-2.3.0.jar:na]
    at com.sun.proxy.$Proxy11.getNewApplication(Unknown Source) ~[na:na]
    at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getNewApplication(ApplicationClientProtocolPBClientImpl.java:167) ~[hadoop-yarn-common-2.3.0.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:186) ~[hadoop-common-2.3.0.jar:na]
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102) ~[hadoop-common-2.3.0.jar:na]
    at com.sun.proxy.$Proxy12.getNewApplication(Unknown Source) ~[na:na]
    at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getNewApplication(YarnClientImpl.java:133) ~[hadoop-yarn-client-2.3.0.jar:na]
    at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.createApplication(YarnClientImpl.java:141) ~[hadoop-yarn-client-2.3.0.jar:na]
    at org.apache.twill.internal.yarn.Hadoop21YarnAppClient.createLauncher(Hadoop21YarnAppClient.java:60) ~[twill-yarn-0.3.0-incubating.jar:0.3.0-incubating]
    at org.apache.twill.internal.yarn.Hadoop21YarnAppClient.createLauncher(Hadoop21YarnAppClient.java:130) ~[twill-yarn-0.3.0-incubating.jar:0.3.0-incubating]
    at org.apache.twill.yarn.YarnTwillPreparer.start(YarnTwillPreparer.java:249) ~[twill-yarn-0.3.0-incubating.jar:0.3.0-incubating]
    at io.fluo.cluster.yarn.YarnAdmin.start(YarnAdmin.java:108) [fluo-cluster-1.0.0-beta-1-SNAPSHOT.jar:1.0.0-beta-1-SNAPSHOT]
    at io.fluo.cluster.yarn.YarnAdmin.main(YarnAdmin.java:263) [fluo-cluster-1.0.0-beta-1-SNAPSHOT.jar:1.0.0-beta-1-SNAPSHOT]
Caused by: java.net.UnknownHostException: null
    ... 21 common frames omitted
Exception in thread "main" java.lang.RuntimeException: java.net.UnknownHostException: Invalid host name: local host is: (unknown); destination host is: "ip-10-1-2-12":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost
    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at org.apache.twill.yarn.YarnTwillPreparer.start(YarnTwillPreparer.java:318)
    at io.fluo.cluster.yarn.YarnAdmin.start(YarnAdmin.java:108)
    at io.fluo.cluster.yarn.YarnAdmin.main(YarnAdmin.java:263)
Caused by: java.net.UnknownHostException: Invalid host name: local host is: (unknown); destination host is: "ip-10-1-2-12":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:783)
    at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:742)
    at org.apache.hadoop.ipc.Client$Connection.<init>(Client.java:400)
    at org.apache.hadoop.ipc.Client.getConnection(Client.java:1448)
    at org.apache.hadoop.ipc.Client.call(Client.java:1377)
    at org.apache.hadoop.ipc.Client.call(Client.java:1359)
    at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206)
    at com.sun.proxy.$Proxy11.getNewApplication(Unknown Source)
    at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getNewApplication(ApplicationClientProtocolPBClientImpl.java:167)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:186)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
    at com.sun.proxy.$Proxy12.getNewApplication(Unknown Source)
    at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getNewApplication(YarnClientImpl.java:133)
    at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.createApplication(YarnClientImpl.java:141)
    at org.apache.twill.internal.yarn.Hadoop21YarnAppClient.createLauncher(Hadoop21YarnAppClient.java:60)
    at org.apache.twill.internal.yarn.Hadoop21YarnAppClient.createLauncher(Hadoop21YarnAppClient.java:130)
    at org.apache.twill.yarn.YarnTwillPreparer.start(YarnTwillPreparer.java:249)
    ... 2 more
Caused by: java.net.UnknownHostException
    ... 21 more
[cluster@ip-10-1-2-10 bin]$ 

```

**Comment by dlnufox** [comment]
Hi, @keith-turner . 
I have the same question. Is it a bug ?

**Comment by keith-turner** [comment]
@dlnufox  can you provide more details about the error you saw?
